app:
  name: "web_app"
  version: "v0.0.1"
  port: "8801"
  start_time: "2020-07-01"
  machine_id: 1
  mode: "dev"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  user: "root"
  password: "mysql"
  dbname: "sql_test"
  port: 3306
  max_open_cons: 200
  max_idle_cons: 50
redis:
  user: "root"
  host: "127.0.0.1"
  port: "6379"
  db: 0
  password: ""
  pool_size: 100
