app:
  name: "web_app"
  mode: "dev"
  port: "8801"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 100
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "mysql"
redis:
  user: "root"
  port: "6379"
  db: 0
